<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
    <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
    
    <!-- 百度api 参数配置 -->
    <div class="form-group">
        <label class="group-name" for="deeplx-api-url">百度 API地址:</label>
        <div class="group-controls">
            <input id="baidu-api-url" required="required" name="BaiduApiUrl" type="text" value="<?php echo FreshRSS_Context::$user_conf->baiduApiUrl; ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="group-name" for="baidu-api-key">APP ID:</label>
        <div class="group-controls">
            <input id="baidu-api-key" required="required" name="BaiduApiKey" type="text" value="<?php echo FreshRSS_Context::$user_conf->baiduApiKey; ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="group-name" for="baidu-api-secret">密钥:</label>
        <div class="group-controls">
            <input id="baidu-api-secret" required="required" name="BaiduApiSecret" type="text" value="<?php echo FreshRSS_Context::$user_conf->baiduApiSecret; ?>">
        </div>
    </div>

    <!-- 订阅源翻译设置 -->
    <div class="form-group">
        <label class="group-name">订阅源翻译设置:</label>
        <div class="group-controls">
            <?php 
            $feeds = FreshRSS_Factory::createFeedDao()->listFeeds();
            if (empty($feeds)): ?>
                <span>暂无订阅源，请添加后重试</span>
            <?php else: ?>
                <?php foreach ($feeds as $id => $feed): ?>
                <li class="form-group">
                    <span class="feed-name"><?php echo $feed->name(); ?></span>
                    <input type="checkbox" id="feed-<?php echo $id; ?>" name="TranslateTitles[<?php echo $id; ?>]" value="1" <?php if (isset(FreshRSS_Context::$user_conf->TranslateTitles[$id]) && FreshRSS_Context::$user_conf->TranslateTitles[$id] == '1') echo ' checked="checked"'; ?>>
                </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>

    <!-- 提交与取消按钮 -->
    <div class="form-group form-actions">
        <div class="group-controls">
            <button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
            <button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
        </div>
    </div>
</form>